---
- !ruby/object:Rubber::Configuration::InstanceItem
  name: production
  domain: harvesthelper.com
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: apache
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: app
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: passenger
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: common
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: db
    options:
      primary: true
  - !ruby/object:Rubber::Configuration::RoleItem
    name: postgresql
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: postgresql_master
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: elasticsearch
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: examples
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graphite_server
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graphite_web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graylog_elasticsearch
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graylog_mongodb
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: mongodb
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graylog_server
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graylog_web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: haproxy
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web_tools
    options: {}
  instance_id: i-edb0b192
  image_type: m1.small
  image_id: ami-eafa5883
  security_groups:
  - Harvest_Helper_production_default
  - Harvest_Helper_production_web
  - Harvest_Helper_production_web_tools
  - Harvest_Helper_production_production
  - Harvest_Helper_production_apache
  - Harvest_Helper_production_app
  - Harvest_Helper_production_passenger
  - Harvest_Helper_production_collectd
  - Harvest_Helper_production_common
  - Harvest_Helper_production_monit
  - Harvest_Helper_production_db
  - Harvest_Helper_production_postgresql
  - Harvest_Helper_production_postgresql_master
  - Harvest_Helper_production_elasticsearch
  - Harvest_Helper_production_examples
  - Harvest_Helper_production_graphite_server
  - Harvest_Helper_production_graphite_web
  - Harvest_Helper_production_graylog_elasticsearch
  - Harvest_Helper_production_graylog_mongodb
  - Harvest_Helper_production_mongodb
  - Harvest_Helper_production_graylog_server
  - Harvest_Helper_production_graylog_web
  - Harvest_Helper_production_haproxy
  external_host: ec2-50-19-24-119.compute-1.amazonaws.com
  external_ip: 50.19.24.119
  internal_host: ip-10-84-249-233.ec2.internal
  internal_ip: 10.84.249.233
  zone: us-east-1d
  platform: linux
  root_device_type: instance-store
- volumes: {}
  static_ips: {}
